spring:
  application:
    name: chat-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILES}
  servlet:
    multipart:
      maxFileSize: 2048MB
      maxRequestSize: 2048MB
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      max-active: 200
      max-wait: 2000